### ISSUE TITLE
how to mix monads in a for comprehension?

### ISSUE THREAD

**Issue by fommil** [fommil/drone-dynamic-agents#10]
in this version of the code https://github.com/fommil/drone-dynamic-agents/blob/4199e9dad3953cd9f5dfb5eee928d3af0a22df23/src/main/scala/oauth2/oauth2.scala#L210-L220

```scala
    def access(code: CodeToken): FreeS[F, (RefreshToken, Option[BearerToken])] = {
      val uri = Uri.parse(config.access.toString).getOrElse(throw new java.lang.IllegalArgumentException("bad uri"))
      val request = AccessRequest(code.token, code.redirect_uri, config.clientId, config.clientSecret)
      for {
        response <- server.postUrlencoded[AccessRequest, AccessResponse](uri, request)
        time <- clock.now
        //refresh = RefreshToken(response.access_token, )
      } yield ???
    }
```

I'd like to just write something like

```scala
      for {
        uri <- Uri.parse(config.access.toString)
        request = AccessRequest(code.token, code.redirect_uri, config.clientId, config.clientSecret)
        response <- server.postUrlencoded[AccessRequest, AccessResponse](uri, request)
        time <- clock.now
```

(i.e. move the `uri` into the for-comp) and have the `Free` deal with the error case (`Uri.parse` returns a scodec `Attempt[Uri]`, which is effectively an `Either[String, Uri]`).

But all my attempts to use monad transformers have failed. An this example / description from @yilinwei isn't quite what I want to do https://gist.github.com/yilinwei/8e3e260dc7a0c9ffb2e5518b8d4d5b9f

**Comment by PaulAtBanno** [comment]
See my comment on #11.
