### ISSUE TITLE
how to deal with the unhappy path

### ISSUE THREAD

**Issue by fommil** [fommil/drone-dynamic-agents#11]
Could be that understanding #10 helps here.

I basically have no idea how to recover from errors / failures or even how to raise them (e.g. when I only want to consider the `Right` of a method call that returns `Either`).

What about the equivalent of `finally`? e.g. say I'm writing something that needs a DB transaction and I can exit early.

**Comment by fommil** [comment]
https://gist.github.com/yilinwei/8e3e260dc7a0c9ffb2e5518b8d4d5b9f#file-free2-scala would suggest that we always need to add an `error` algebra element that allows for early exit and interpreter specific reporting.

**Comment by fommil** [comment]
this seems to be the answer http://frees.io/docs/effects/#error

**Comment by PaulAtBanno** [comment]
Yep. And your observation that you want an answer to #10 is spot on, too.

There are three general strategies for combining monads:

1. Monad transformers. They kept me away from Haskell.
2. Monad coproducts. Rúnar wrote about them [here](http://functionaltalks.org/2014/11/23/runar-oli-bjarnason-free-monad/); the video has moved [here](https://www.youtube.com/watch?v=M258zVn4m2M).
3. Some variant of [extensible effects](http://okmij.org/ftp/Haskell/extensible/). Freestyle appears to be/offer such a thing, as you see with the error effect. Another such library that supports the concepts and has both Cats and scalaz modules is [Eff](http://atnos-org.github.io/eff/).

Finally, there's the lazy approach:

1. Shove everything into a _big_ monad, e.g. scalaz's or fs2's `Task`.

I'm guilty of this a lot. For example, as an http4s/scalaz developer, I've certainly written:

```scala
for {
  uri <- Task.fromDisjunction(Uri.fromString("..."))
  foo <- client.expect[Foo](uri)
} yield foo
```

to do a GET on a URI I only know at runtime, and rely on `Task` to model failure as well as success.

**Comment by fommil** [comment]
Example of something that confuses me: try/finally cleanup in a Monad. Is it possible? Doobie may have inspiration.

**Comment by fommil** [comment]
Catachable and Suspendable

**Comment by wedens** [comment]
`MonadError` is the most generic abstraction capable of doing it

**Comment by wedens** [comment]
The problem with `error` effect from freestyle is that the only error type is `Throwable`.

**Comment by raulraja** [comment]
Yes, it defaults to Throwable but we are about to introduce `either` which
will allow you to set the E to any type and the constrain will be on
MonadError[M, E]. For the time being feel free to roll your own algebra
based on the ErrorM sources, should be straightforward and I can help if
you get stuck. Also if you want to contribute this effect we are open for
contributions and there are other examples of algebras parameterized such
as the ones for the reader, writer and state effects.

**Comment by raulraja** [comment]
@fommil Do you have an ADT for your error types? I may be able to provide an example of using the actual `error` effect to achieve what you want or an `either` algebra that would be parametrized over `E`.

**Comment by fommil** [comment]
@raulraja I'm starting to think about this in more detail. Is there an example of doing `try` / `finally` in `FreeS` and/or `FreeApplicable`. I mean for expected errors and unexpected errors... what if an implementation just unexpectedly throws an exception and I **really** need to close a resource.

**Comment by fommil** [comment]
@vmarquez apologies for taking so long to ping you about this, which is the issue we discussed at Lambdaconf. I think I understand what `Error` is doing, but I'm still a bit lost about how to do `finally`. You said this could be done in the interpreter if it is a `Task` (presumably, and less safe, this could be done with `Future` too).

The specific algebra I want to wrap with a try/finally is `UserInteraction` in https://github.com/fommil/drone-dynamic-agents/blob/master/src/main/scala/http/oauth2.scala which looks like

```
  @free trait UserInteraction {
    /** returns the Uri that the local server is listening on */
    def start: FS[Uri]
    /** prompts the user to open this Uri, which will end up at the local server */
    def open(uri: Uri): FS[Unit]
    /** wait for the user interaction to complete and recover the code */
    def stop: FS[CodeToken]
  }
```

first of all, it has been pointed out that this should *anyway* be an `IndexedMonad` to enforce the ordering, but secondly (and more important) if `start` is called, any exit from the use of this algebra (be it in the anticipated unhappy path or an unexpected exception raised elsewhere) then the local HTTP server should be discarded (in which case maybe `stop` could be redesigned as `read`).

Any thoughts greatly appreciated. I'm slowing padding out the implementation of this app as I'm writing https://leanpub.com/fp-scala-mortals

**Comment by fommil** [comment]
I learnt about `MonadError` this week... it *seems* to be exactly what I want. I just need to work out how to tell the business logic that the algebra must be a `MonadError`... and it would be even nicer if implementations could only exist that *always* have the failure handling case applied. Plus the `IndexedMonad` stuff too.

**Comment by raulraja** [comment]
@fommil The `error` effect imposes the constrain of `M[_] : MonadError[M, Throwable]`. You may just use it in place of defining your own algebra but if you wanted to define it for illustrative purposes here is how you'd satisfy: `implementations that always have the failure case applied` : https://github.com/frees-io/freestyle/blob/master/freestyle-effects/shared/src/main/scala/effects/error.scala#L35

For example if you use the error effect you can't interpret to `Id` because you'd have to implement `MonadError[Id, Throwable]` and you'll find that the only way `Id` can satisfy those constrains is by throwing the exception and that is why cats does not provide an instance of `MonadError` for `Id`
