### ISSUE TITLE
is the UserInteraction really just an IndexedStateMonad?

### ISSUE THREAD

**Issue by fommil** [fommil/drone-dynamic-agents#12]
not everything has to be a `Free`...

**Comment by edmundnoble** [comment]
Free is for abstracting over monads. That's the entire purpose. You are losing that power by fixing a monad.

**Comment by fommil** [comment]
I don't think I understand what you mean.

**Comment by edmundnoble** [comment]
I uh... don't think I understand what you mean either. Can you elaborate on the issue name?

**Comment by fommil** [comment]
I was told that sometimes when I'm modelling as a Free Algebra already exists as an Effect, and in this case the Monad in the title was suggested... perhaps with some extra checks or something?

**Comment by larsrh** [comment]
If you need extra checks you can also define a wrapper type around `IndexedState`. Judging by the sources it would probably make sense to do that, because it looks like you need to enforce some call ordering (`start`/`stop`). I'm not sure whether or not that is possible with `Free`.

**Comment by fommil** [comment]
Does `IndexedState` have any extra compile time checks or is it all runtime?

Also, having the `Monad` handle its own cleanup is something I'm completely unsure about when writing an interpreter. Is that possible? for this algebra, if anything fails I want the monad to take care of tearing down the local webserver.
