### ISSUE TITLE
Are you aware of Gitlab CI/CD pipelines?

### ISSUE THREAD

**Issue by bagrounds** [fommil/drone-dynamic-agents#20]
"For many libre software projects, requiring a few hours of compute time every day, this can make it possible to use high-powered build machines for a fraction of the cost of a dedicated machine (e.g. $20/month instead of $200/month)."

https://about.gitlab.com/features/gitlab-ci-cd/

Free use of shared runners for public and private repos.

**Comment by fommil** [comment]
Thanks. This project is primarily the demo app for a book.

I've used every CI/CD out there and I doubt gitlab is offering higher powered machines than anybody else. I couldn't find specs, do you know them?

**Comment by bagrounds** [comment]
My comment was purely informational. It looks (to me) like you're assuming that it costs money to use cloud hosted CI/CD servers - I'm just pointing out that GitLab actually offers this service for free.

I don't know the specs for their machines off hand - but my only point was that they're free to use.

Earlier this year, they introduced limits for private repos, but I believe public repos still have unlimited use of their CI servers.

https://about.gitlab.com/2017/04/11/introducing-subscriptions-on-gitlab-dot-com/
"Thanks to the generosity of Digital Ocean we were able to offer unlimited CI minutes for the last year. Over this time, we've run billions of free CI minutes across thousands of projects on GitLab.com.

We are going to continue to give away free CI, but from May 1st, the number of minutes on our shared runners will be capped at 2000 minutes a month per group and our paid plans will allow for additional minutes. **This limit will only apply to private projects**. This will affect less than 3% of all groups using CI on GitLab.com today. 2000 minutes means you can run a pipeline of 10 minutes five times a day, every working day."

**Comment by fommil** [comment]
I'm very interested in gitlab in general, so I might use it for new projects. I very much like that all the software is free / libre (what is the CI runner and is it also free / libre like the core repo hosting?). Nevertheless, drone works with gitlab so I can use drone-dynamic-agents with it when it is finished. Like I said, the primary purpose of this application has become the demo application for https://leanpub.com/fp-scala-mortals rather than the application in its own right, so progress is much much slower than it would have been.

**Comment by fommil** [comment]
(btw, I tried Digital Ocean directly and their machines are *waaaay* under powered to handle a build like the `ensime/ensime-server` project)

**Comment by bagrounds** [comment]
> what is the CI runner and is it also free / libre like the core repo hosting?

https://gitlab.com/gitlab-org/gitlab-ci-multi-runner

**Comment by fommil** [comment]
Sweet. I think i might start moving over.

**Comment by fommil** [comment]
FYI I've moved over this project https://gitlab.com/fommil/stalactite

and I was impressed that all the issues were imported.

However, I am missing a few things that I feel are critical to my CI workflow. Especially matrix builds, I'm finding it very hard to duplicate the simplicity of travis / drone `matrix:` sections that simply run the same file with different environment variables.

Beyond that, I'm still trying to work out how to protect `master` (i.e. require that everything goes through a green PR) and a CLA checker that contributors must sign.

**Comment by fommil** [comment]
@bagrounds the above issues aside, you just got yourself a new paying customer :stuck_out_tongue: (I believe in Free / Libre, but I don't believe in Free / Gratis).

**Comment by fommil** [comment]
@bagrounds omg omg omg you support custom Runners out of the box, this is amazing, this is so amazing. I'm creating a ticket to add support for this CI.
