### ISSUE TITLE
idiomatic alternative to extractors

### ISSUE THREAD

**Issue by fommil** [fommil/drone-dynamic-agents#3]
I wrote the business logic to pattern match / extract on the `WorldView`, to do scenario detection, followed by the action.

But this feels ugly because it splits detection from action (I'd rather they were together) and also means I don't get type exhaustivity checking in the pattern match (hence `case _ =>` at the bottom).

What's the idiomatic way to structure this code?

**Comment by yilinwei** [comment]
**/cc** @zainab-ali

**Comment by zainab-ali** [comment]
Funnily enough, I have pretty much the same problem.  I have lots of different kinds of state, and different kinds of events.  I want a nice way of writing and composing event / state combinations.

Thus far, I've come up with the idea of a [handler](https://gist.github.com/zainab-ali/bd48e897739a4429f409336860a341d0).  This has an `accept` function which acts on an event and an input state to determine if the event is valid.  It also has a `handle` function which acts on the state.

The game is a composition of handlers.  

The code itself is very rough (names are verbose), but maybe that might be what you're looking for?
