### ISSUE TITLE
how to do node stopping in parallel?

### ISSUE THREAD

**Issue by fommil** [fommil/drone-dynamic-agents#6]
in the `act` `Stale` branch, the ideal situation would be to send off all the `stop` requests in parallel and then process the responses to add the `WorldView` update. The order doesn't matter, so long as the update step is sequential.

If any of the `stop` requests fail, it shouldn't stop the others from proceeding.

The biggest issue with the current code is that one of the nodes could take a long time to `stop`, and then we end up stopping the next one once it's gone over its 60 minute billing cycle.

**Comment by PaulAtBanno** [comment]
I can't find the referenced branch.

**Comment by fommil** [comment]
This is in the logic.scala file

**Comment by fommil** [comment]
I'm writing this part of the book now, so any help would be appreciated. This is the current (sequential) code

```
      nodes.foldM(world) { (world, n) =>
        for {
          _ <- c.stop(n)
          update = world.copy(pending = world.pending + (n -> world.time))
        } yield update
      }
```

I could guess that I would `map` over the `world` and then fold over the results... but what happens in the unhappy path case? In my current code, each stop / `world` update happens sequentially so I get early exit (potentially with the most recent valid `world`) but if everything happens in parallel I want to still be able to update the world view for each of the operations that **did** succeed.

**Comment by fommil** [comment]
awesome, thanks Raul!
