### ISSUE TITLE
Reader / Writer interpreters for testing

### ISSUE THREAD

**Issue by fommil** [fommil/drone-dynamic-agents#9]
@tpolecat noted in `typelevel/cats` that a `Reader` / `Writer` interpreter for any algebra should be easy enough to write.

If it is that easy, then a macro that does this would be of **huge** benefit to the community (automatic mocks!) but in the meantime, writing some for my simple algebras and replacing the `var` backed interpreters would be a win.

**Comment by raulraja** [comment]
@fommil I'm not a guru... but, if you just want to use `Reader` and `Writer` as effects in those algebras, there is `freestyle-effects` that already implements those. The constrains those effects place in the interpreters is that your final interpretation should be targeting a Monad that supports both `MonadReader` and `MonadWriter`.

A transformer stack that supports those effects may be for example:

```scala
type Log = List[String] //writer target
type WR[A] = WriterT[Future, Log, A] // writer t parameterized to your concurrent runtime monad
type Target[A] = ReaderT[WR, Config, A] // Reader that provides Config as dependency and it's parameterized to your writer stack
```
or if using kind projector
```scala
type Target[A] = ReaderT[WriterT[Future, List[String], ?], Config, A]
```
You should be able to just run your free programs that have some of those effects in your compositions to a target similar to this one providing you have the appropriate cats and freestyle implicits.

If you go down that path and need help let me know. :)

**Comment by fommil** [comment]
I definitely will!

**Comment by PaulAtBanno** [comment]
I admit to being confused here by using monad transformers; it looks like Freestyle's annotations `@free` and `@module` are precisely about combining monads!

**Comment by fommil** [comment]
Yup but @tpolecat was suggesting a macro that generates a complete interpreter for an Algebra, using reader/writer. And also one for logging. I have no idea where to start, but he seemed to think it was easy.

**Comment by tpolecat** [comment]
>  @tpolecat was suggesting a macro

I was not suggesting a macro. I was suggesting that for your case where you have an `Id` interpreter it would be straightforward to create a logging interpreter in `Writer` on top of it.

In general I'm skeptical of the value of any automation on top of `Free`. I have not felt the need for it.

**Comment by raulraja** [comment]
@fommil regardless of freestyle you are in `Free` and need state / reader / writer you don't need anything but flag your target `M[_]` in your FunctionK to be constrains by implicit evidences of `MonadReader`, `MonadWriter` and `MonadState` respectively. This is what some people call the MTL typeclasses and they are just used to add Syntax on top of monad based computations. Then you can place the ops you need in your algebra and just use the implicits in the interpreter. When you run your interpreter against Free it will require that `M[_]` has evidence of those typeclasses instances and your ops will be automatically delegated to the instance found. Alternatively you can use `FreeT` which is the Free transformer and it allows a stacked monad beside the algebra which you can intermix in your program.

There is an example using `FreeT` here with `MonadState` http://typelevel.org/cats/datatypes/freemonad.html

@tpolecat IMO the automation is needed when you have multiple algebras and not just a single one. If you add some kind of hierarchical org around those,  generalize the implicit resolution of Coproduct for all the algebras, parallelization steps over Free and others that are usually needed in large apps, building all the Free boilerplate becomes 90% of your code. I'd love to show you in person next time we see each other over :beers: what we are doing with Freestyle, it's a lot more than a macro to remove the ADTs boilerplate.
